Theme dark&light
Droidion/opus-classical-golang pull request #11
Opened 2023-03-27 23:22 UTC by redaktorscha

Add color themed styles (dark&light), a theme switcher, script for handling theme change and storing user preferences

2023-03-28 08:25 UTC, Droidion commented
404 picture should be entered, both horizontally and vertically.

<img width="1394" alt="CleanShot 2023-03-28 at 11 22 43@2x" src="https://user-images.githubusercontent.com/2992696/228175335-9444a24e-dd93-4ad2-81de-03c2d0fcdbab.png">

2023-03-28 08:31 UTC, Droidion commented
Compare picture size of 404 picture of webp vs svg. If webp is noticeably smaller, use webp.

2023-03-29 07:20 UTC, Droidion requested changes

2023-03-29 07:20 UTC, Droidion commented on scripts/theme.ts
> +  )! as HTMLInputElement;
Don't use `!` in the file, you have no real not-null guarantees. Handle potential nulls.

2023-03-29 07:20 UTC, Droidion commented on scripts/theme.ts
> +const setColorTheme = (colorTheme: string): void => {
Change `colorTheme` to `themeName` and remove parameter from JSDoc, because it won't convey new information then.

2023-03-29 07:20 UTC, Droidion commented on scripts/theme.ts
> +export default (() => {
Have this in `main.ts`, export `defineColorThemeOnLoad` from here, don't generate separate file with `esbuild`.

2023-03-31 13:10 UTC, redaktorscha commented on scripts/theme.ts
> +export default (() => {
done

2023-04-04 20:19 UTC, Droidion approved these changes

2023-04-04 20:19 UTC, merged